import {describe,it,expect} from 'vitest';
import {cargoOptions,eligibleStation,planRoutes,travel} from '../src/lib/planner';import {defaultSettings,defaultShip,type Station,type Snapshot,type Commodity} from '../src/lib/types';import {normalizeStation,normalizeSnapshot} from '../server/normalize';import {marketQuery} from '../server/provider';import {snapshotSchema,shipSchema,settingsSchema} from '../src/lib/validation';import {routeCSV} from '../src/lib/format';
const commodity=(key:string,buy:number,sell:number,supply=10000,demand=10000):Commodity=>({key,name:key,category:'Metals',buy,sell,supply,demand});
function station(id:string,commodities:Commodity[],x=0):Station{return {id,name:id,system:id,systemId:id,x,y:0,z:0,distance:x,arrival:100,pad:3,planetary:false,carrier:false,permit:false,permitKnown:true,prohibited:[],services:['Market'],type:'Orbis',updated:new Date().toISOString(),commodities};}
function snap(stations:Station[]):Snapshot{return {stations,reference:{name:'A',id:'A',x:0,y:0,z:0},fetchedAt:new Date().toISOString(),source:'Test fixture',total:stations.length,loaded:stations.length,truncated:false,warnings:[],radius:80};}
const ship={...defaultShip,cargo:10,budget:100000,reserve:1000};const options={...defaultSettings,startStation:'A',hops:3,minMargin:1,haircut:0,demandFraction:1,fuelCost:0,maxMinutes:600};
describe('cargo allocation',()=>{
 it('uses player-perspective buy and sell prices',()=>{const a=station('A',[commodity('gold',100,90)]),b=station('B',[commodity('gold',200,300)]);const load=cargoOptions(a,b,ship,options,100000)[0];expect(load.cost).toBe(1000);expect(load.profit).toBe(2000);});
 it('reserves insurance and stays within an affordable cargo manifest',()=>{const a=station('A',[commodity('gold',100,0)]),b=station('B',[commodity('gold',0,300)]);const load=cargoOptions(a,b,ship,options,1550)[0];expect(load.quantity).toBe(5);expect(load.cost).toBeLessThanOrEqual(550);});
 it('fills with a second commodity when high-margin supply is limited',()=>{const a=station('A',[commodity('gold',100,0,4),commodity('silver',10,0)]),b=station('B',[commodity('gold',0,300),commodity('silver',0,100)]);const load=cargoOptions(a,b,ship,options,100000)[0];expect(load.quantity).toBe(10);expect(load.cargo).toHaveLength(2);expect(load.profit).toBe(1340);});
 it('caps demand and excludes zero demand',()=>{const a=station('A',[commodity('gold',100,0)]),b=station('B',[commodity('gold',0,300,0,20)]);expect(cargoOptions(a,b,ship,{...options,demandFraction:.1},100000)[0].quantity).toBe(2);b.commodities[0].demand=0;expect(cargoOptions(a,b,ship,options,100000)).toEqual([]);});
 it('consumes branch-local stock and demand on revisits',()=>{const a=station('A',[commodity('gold',100,0,10)]),b=station('B',[commodity('gold',0,300,0,10)]);expect(cargoOptions(a,b,ship,options,100000,{'s:A:gold':8,'d:B:gold':9})[0].quantity).toBe(1);expect(cargoOptions(a,b,ship,options,100000,{'s:A:gold':10})).toEqual([]);});
 it('filters illegal and excluded commodities at either end',()=>{const a=station('A',[commodity('gold',100,0)]),b=station('B',[commodity('gold',0,300)]);b.prohibited=['gold'];expect(cargoOptions(a,b,ship,options,100000)).toEqual([]);b.prohibited=[];expect(cargoOptions(a,b,ship,{...options,excluded:'Gold'},100000)).toEqual([]);});
 it('applies the sale safety margin once',()=>{const a=station('A',[commodity('gold',100,0)]),b=station('B',[commodity('gold',0,300)]);expect(cargoOptions(a,b,ship,{...options,haircut:.1},100000)[0].profit).toBe(1700);});
 it('keeps single-commodity mode single',()=>{const a=station('A',[commodity('gold',100,0,4),commodity('silver',10,0)]),b=station('B',[commodity('gold',0,300),commodity('silver',0,100)]);expect(cargoOptions(a,b,ship,{...options,mixed:false},100000).every(l=>l.cargo.length===1)).toBe(true);});
});
describe('path search',()=>{
 const a=station('A',[commodity('gold',100,0),commodity('copper',0,300)],0),b=station('B',[commodity('gold',0,300),commodity('silver',100,0)],10),c=station('C',[commodity('silver',0,300),commodity('copper',100,0)],20);
 it('finds A → B → C rather than forcing B → A',()=>{const r=planRoutes(snap([a,b,c]),ship,{...options,hops:2,objective:'profit'}).routes[0];expect(r.legs.map(l=>l.to.id)).toEqual(['B','C']);expect(r.profit).toBe(4000);});
 it('can revisit A at the end of a profitable multi-stop loop',()=>{const r=planRoutes(snap([a,b,c]),ship,{...options,mode:'loop',objective:'profit'}).routes[0];expect(r.legs.map(l=>l.to.id)).toEqual(['B','C','A']);expect(r.profit).toBe(6000);expect(r.terminal).toBeUndefined();});
 it('includes empty return time and fuel for a loop without return cargo',()=>{const r=planRoutes(snap([a,b]),ship,{...options,mode:'loop',hops:1,fuelCost:100}).routes[0];expect(r.terminal?.id).toBe('A');expect(r.terminalMinutes).toBeGreaterThan(0);expect(r.profit).toBe(1800);});
 it('finishes destination routes at the requested system',()=>{const r=planRoutes(snap([a,b,c]),ship,{...options,mode:'destination',destination:'C',objective:'profit'}).routes[0];expect(r.terminal?.system??r.legs.at(-1)?.to.system).toBe('C');});
 it('does not pretend an unreachable station is reachable',()=>{const far=station('B',[commodity('gold',0,300)],1000);expect(planRoutes(snap([a,far]),ship,{...options,maxJumps:1}).routes).toEqual([]);});
 it('enforces session duration and keeps ending balance correct',()=>{const rs=planRoutes(snap([a,b,c]),ship,{...options,maxMinutes:15}).routes;expect(rs.every(r=>r.minutes<=15&&r.balance===ship.budget+r.profit)).toBe(true);});

 it('deducts positioning fuel before the first cargo purchase',()=>{const d=snap([b,c]);d.reference={name:'Origin',id:'Origin',x:-20,y:0,z:0};const r=planRoutes(d,ship,{...options,startStation:'',hops:1,fuelCost:100}).routes[0];expect(r.balance).toBeCloseTo(ship.budget+r.profit);expect(r.profit).toBeLessThan(2000);expect(r.initialMinutes).toBeGreaterThan(0);});
 it('never exceeds a commodity supply over repeated loops',()=>{const limited={...a,commodities:a.commodities.map(g=>({...g,supply:10}))};const rs=planRoutes(snap([limited,b,c]),ship,{...options,hops:6,objective:'profit'}).routes;for(const r of rs){const used=r.legs.filter(l=>l.from.id==='A').flatMap(l=>l.cargo).filter(g=>g.key==='gold').reduce((n,g)=>n+g.quantity,0);expect(used).toBeLessThanOrEqual(10);}});
 it('shows a helpful error for a missing starting market',()=>{const r=planRoutes(snap([a,b]),ship,{...options,startStation:'Missing'});expect(r.routes).toEqual([]);expect(r.warnings[0]).toContain('starting station');});
 it('rejects stale, small-pad and restricted markets',()=>{const s=station('S',[commodity('gold',100,300)]);s.updated='2020-01-01T00:00:00Z';expect(eligibleStation(s,ship,options)).toBe(false);s.updated=new Date().toISOString();s.pad=2;expect(eligibleStation(s,ship,options)).toBe(false);s.pad=3;s.permit=true;expect(eligibleStation(s,ship,options)).toBe(false);});
 it('counts no hyperspace jumps between stations in the same system',()=>{const d={...b,systemId:'A',system:'A',x:0};expect(travel(a,d,ship,options).jumps).toBe(0);});
 it('exports escaped names with original timestamps',()=>{const r=planRoutes(snap([{...a,name:'A, "Dock"'},b]),ship,{...options,startStation:'A, "Dock"',hops:1}).routes[0];expect(routeCSV(r)).toContain('"A, ""Dock"""');expect(routeCSV(r)).toContain(a.updated);});
});
describe('provider and input validation',()=>{
 it('normalizes verified Spansh fields without swapping buy/sell',()=>{const s=normalizeStation({market_id:123,name:'Dock',system_name:'Sol',system_id64:1,system_x:0,system_y:0,system_z:0,large_pads:1,type:'Orbis',market_updated_at:new Date().toISOString(),market:[{commodity:'Gold',buy_price:100,sell_price:90,supply:50,demand:100}]})!;expect(s.commodities[0]).toMatchObject({key:'gold',buy:100,sell:90,supply:50});expect(s.pad).toBe(3);});
 it('ignores invalid coordinates',()=>{expect(normalizeStation({name:'Dock',system_name:'Sol',market_id:1,system_x:null,system_y:0,system_z:0})).toBeNull();});
 it('requires valid reference coordinates',()=>{expect(()=>normalizeSnapshot([{results:[],count:0}],80)).toThrow('reference system');});
 it('bounds provider requests',()=>{expect(marketQuery.safeParse({system:'Sol',radius:999}).success).toBe(false);expect(marketQuery.parse({system:'Sol'}).radius).toBe(80);});
 it('rejects corrupted snapshots and unsafe settings',()=>{expect(snapshotSchema.safeParse({stations:[]}).success).toBe(false);expect(shipSchema.safeParse({...ship,jump:0}).success).toBe(false);expect(settingsSchema.safeParse({...options,mode:'destination',destination:''}).success).toBe(false);});
});
