import {useMemo,useState} from 'react';import {Search,Download,ArrowUpDown} from 'lucide-react';import type {Snapshot} from '../lib/types';import {age,number,download} from '../lib/format';
export default function Markets({snapshot,onLoad,busy,onStart}:{snapshot:Snapshot|null;onLoad:()=>void;busy:boolean;onStart:(system:string,station:string)=>void}){
 const [query,setQuery]=useState(''),[direction,setDirection]=useState<'buy'|'sell'>('buy'),[sort,setSort]=useState<'price'|'age'>('price'),[page,setPage]=useState(0);
 const rows=useMemo(()=>snapshot?.stations.flatMap(station=>station.commodities.map(c=>({...c,station}))).filter(c=>`${c.name} ${c.station.name} ${c.station.system}`.toLowerCase().includes(query.toLowerCase())&&(direction==='buy'?c.buy>0&&c.supply>0:c.sell>0&&c.demand>0)).sort((a,b)=>sort==='age'?Date.parse(b.station.updated)-Date.parse(a.station.updated):direction==='buy'?a.buy-b.buy:b.sell-a.sell)??[],[snapshot,query,direction,sort]);
 return <section className="panel markets-panel"><div className="panel-title"><h2>Commodity markets</h2><button type="button" className="outline" disabled={busy} onClick={onLoad}>{busy?'Loading…':'Refresh markets'}</button></div><div className="market-controls"><div className="search-field"><Search size={17}/><input aria-label="Search commodities, stations and systems" placeholder="Commodity, station or system…" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></div><select aria-label="Market direction" value={direction} onChange={e=>{setDirection(e.target.value as 'buy'|'sell');setPage(0);}}><option value="buy">Places to buy</option><option value="sell">Places to sell</option></select><button type="button" className="outline" onClick={()=>setSort(sort==='price'?'age':'price')}><ArrowUpDown size={15}/>{sort==='price'?'Best price':'Newest data'}</button>{snapshot&&<button type="button" className="icon-button" aria-label="Export market snapshot" onClick={()=>download('edtrade-markets.json',JSON.stringify(snapshot))}><Download size={16}/></button>}</div>
 <p className="market-scope">{snapshot?`${snapshot.loaded} markets loaded around ${snapshot.reference.name}. This is the current snapshot; refresh to apply new area filters.`:'Load markets using your ship and search preferences. Prices are displayed from the player’s perspective.'}</p>
 <div className="table-scroll"><table><thead><tr><th>Commodity</th><th>System / station</th><th>{direction==='buy'?'Buy price':'Sell price'} (Cr/t)</th><th>{direction==='buy'?'Supply':'Demand'}</th><th>Pad / approach</th><th>Updated</th><th>Start</th></tr></thead><tbody>{rows.slice(page*30,(page+1)*30).map(c=><tr key={c.station.id+':'+c.key}><td>{c.name}<small>{c.category}</small></td><td>{c.station.system}<small>{c.station.name}</small></td><td className={direction==='sell'?'mint':''}>{number(direction==='buy'?c.buy:c.sell)}</td><td>{number(direction==='buy'?c.supply:c.demand)}</td><td>{['?','S','M','L'][c.station.pad]} · {c.station.arrival===null?'?':number(c.station.arrival)} ls</td><td title={c.station.updated}>{age(c.station.updated)}</td><td><button type="button" className="outline" onClick={()=>onStart(c.station.system,c.station.name)}>Plan here</button></td></tr>)}</tbody></table></div>{!rows.length&&<div className="market-no-results">{snapshot?'No matching commodity quotes. Try another search or refresh with broader filters.':'Your market explorer is ready. Choose “Refresh markets” to fetch observed quotes.'}</div>}
 <div className="run-footer"><span>{number(rows.length)} quotes · prices exclude any sale safety margin</span><div className="toolbar"><button type="button" className="outline" disabled={page===0} onClick={()=>setPage(page-1)}>Previous</button><span>{page+1} / {Math.max(1,Math.ceil(rows.length/30))}</span><button type="button" className="outline" disabled={(page+1)*30>=rows.length} onClick={()=>setPage(page+1)}>Next</button></div></div></section>;
}
