import {useState} from 'react';import {Bookmark,Download,Copy,ChevronDown,Route as RouteIcon,ArrowRight,Check,Navigation,Share2} from 'lucide-react';
import type {Route,PlanResult} from '../lib/types';import {age,credits,duration,number,routeCSV,download} from '../lib/format';
export default function RouteView({result,selected,setSelected,onSave,completed,setCompleted,onReplan,notify,stale,historical,onShare}:{result:PlanResult|null;selected:number;setSelected:(n:number)=>void;onSave:()=>void;completed:number;setCompleted:(n:number)=>void;onReplan:()=>void;notify:(s:string)=>void;stale:boolean;historical:boolean;onShare:()=>void}){
 const [expanded,setExpanded]=useState<number|null>(0);const r=result?.routes[selected];
 async function copy(s:string){try{await navigator.clipboard.writeText(s);notify('Copied destination system.');}catch{notify('Clipboard unavailable. Select and copy the system name.');}}
 if(!r)return <section className="panel empty-route"><div className="panel-title"><h2>Your trading run</h2></div><div className="empty-body"><div className="empty-route-icon"><RouteIcon size={40}/></div><h3>{result?'No route fits these settings':'Your next profitable stop starts here.'}</h3><p>{result?'Try a wider search, older market data or a lower minimum margin. Check that your starting station matches an eligible market.':'Set up your ship and choose a starting system. EDTrade will compare multi-stop paths using observed market prices.'}</p><div className="empty-features"><span><Check size={15}/> Ship-aware planning</span><span><Check size={15}/> Multiple commodities</span><span><Check size={15}/> No forced A–B loop</span></div></div></section>;
 return <section className="panel route-panel"><div className="panel-title"><h2>Your trading run</h2><div className="toolbar"><button className="outline" type="button" onClick={onSave}><Bookmark size={15}/> Save route</button><button type="button" className="outline" onClick={()=>download('edtrade-route.csv',routeCSV(r),'text/csv;charset=utf-8')}><Download size={15}/> CSV</button><button type="button" className="icon-button" onClick={onShare} aria-label="Copy setup link" title="Copy setup link"><Share2 size={15}/></button></div></div>
 {historical&&<div className="notice">Saved historical route: prices and availability have not been refreshed. Run a new search before departure.</div>}
 {stale&&<div className="notice">Settings changed. This route still uses the configuration from your last search.</div>}
 <div className="alternatives" aria-label="Route alternatives">{result!.routes.slice(0,4).map((route,i)=><button type="button" key={route.id} onClick={()=>{setSelected(i);setCompleted(0);setExpanded(0);}} className={selected===i?'active':''}>{i===0?'Best match':`Alternative ${i}`}<small>{credits(route.rate)} Cr/h · {route.legs.length} legs</small></button>)}</div>
 <div className="metrics"><div><span>Estimated profit</span><strong className="mint">{credits(r.profit)} <small>Cr</small></strong></div><div><span>Estimated credits / hour</span><strong className="mint">{credits(r.rate)} <small>Cr/h</small></strong></div><div><span>Estimated travel time</span><strong>{duration(r.minutes)} <small>({r.legs.reduce((sum,l)=>sum+l.jumps,0)} trade jumps)</small></strong></div></div>
 {r.initialMinutes>0&&<p className="transfer-note"><Navigation size={14}/> Allow {duration(r.initialMinutes)} to reach {r.legs[0].from.name} before buying. First purchase travel is included.</p>}
 <div className="itinerary-header"><span>LEG / STATIONS</span><span>CARGO & RETURN</span><span>PROGRESS</span></div>
 <div className="itinerary">{r.legs.map((l,i)=><article className={'leg '+(i<completed?'complete':'')} key={i}><div className="leg-main"><button type="button" className="leg-destination" onClick={()=>setExpanded(expanded===i?null:i)} aria-expanded={expanded===i}><span className="leg-number">{i+1}</span><div><span className="station-pair">{l.from.name} <ArrowRight size={13}/> {l.to.name}</span><span className="systems">{l.from.system} → {l.to.system}</span><small>{l.distance.toFixed(1)} ly · {l.jumps} jumps · {duration(l.minutes)}</small></div></button><div className="cargo-summary"><b>{l.cargo[0].name}{l.cargo.length>1?` + ${l.cargo.length-1}`:''}</b><span>{number(l.quantity)} t · <strong className="mint">+{credits(l.profit)} Cr</strong></span></div><div className="leg-tools"><button type="button" className="icon-button" aria-label={'Copy '+l.to.system} onClick={()=>copy(l.to.system)}><Copy size={15}/></button><input type="checkbox" aria-label={'Complete trade leg '+(i+1)} checked={i<completed} onChange={()=>setCompleted(i<completed?i:i+1)}/><button type="button" className="icon-button" aria-label={'Expand trade leg '+(i+1)} onClick={()=>setExpanded(expanded===i?null:i)}><ChevronDown size={15} className={expanded===i?'rotated':''}/></button></div></div>
 {expanded===i&&<div className="leg-details"><div className="market-times"><span>Buy: {age(l.from.updated)} · {l.from.arrival===null?'unknown':number(l.from.arrival)} ls · {l.from.type}</span><span>Sell: {age(l.to.updated)} · {l.to.arrival===null?'unknown':number(l.to.arrival)} ls · {l.to.type}</span></div><div className="table-scroll"><table><thead><tr><th>Commodity</th><th>Tonnes</th><th>Buy Cr/t</th><th>Quoted sell Cr/t</th><th>Est. profit</th></tr></thead><tbody>{l.cargo.map(c=><tr key={c.key}><td>{c.name}<small>Supply {number(c.supply)} · demand {number(c.demand)}</small></td><td>{number(c.quantity)}</td><td>{number(c.buy)}</td><td>{number(c.sell)}</td><td className="mint">+{credits(c.profit)}</td></tr>)}</tbody></table></div><div className="leg-finances"><span>Purchase {number(l.cost)} Cr</span><span>Balance after sale ≈ {number(l.balance)} Cr</span></div></div>}
 </article>)}</div>
 {r.terminal&&<p className="transfer-note"><Navigation size={14}/> Final empty transfer to {r.terminal.name}, {r.terminal.system} · {duration(r.terminalMinutes)}. Included in time and fuel estimates.</p>}
 <div className="run-footer"><span>{completed} / {r.legs.length} legs completed · {Math.round(result!.elapsedMs)} ms search</span><button type="button" className="outline orange" disabled={!completed} onClick={onReplan}><Navigation size={15}/> Replan from completed stop</button></div>
 <div className="route-notes"><b>Plan conservatively.</b> Profit includes the sale safety margin and estimated transfer fuel cost. Unknown or zero demand is excluded. Actual quotes can change.</div></section>;
}
export function routeEnd(r:Route,n:number){return r.legs[Math.max(0,Math.min(r.legs.length-1,n-1))];}
