import {useState} from 'react';import type {Route} from '../lib/types';import {Crosshair} from 'lucide-react';import {routeStops} from '../lib/presentation';
export default function RouteMap({route,onGalaxy}:{route?:Route;onGalaxy:()=>void}){
 const [view,setView]=useState<'2d'|'3d'>('2d');const nodes=route?routeStops(route).map(s=>s.station):[];
 // Rotate the actual coordinates to place the dominant route direction vertically.
 const raw=nodes.map(n=>({x:view==='2d'?n.x:n.x-n.z*.55,y:view==='2d'?n.z:n.y*.65+n.z*.4+n.x*.2}));
 const first=raw[0],last=raw.at(-1),angle=first&&last?Math.atan2(last.y-first.y,last.x-first.x)-Math.PI/2:0;
 const rotated=raw.map(p=>({x:p.x*Math.cos(angle)+p.y*Math.sin(angle),y:-p.x*Math.sin(angle)+p.y*Math.cos(angle)}));
 const xs=rotated.map(n=>n.x),ys=rotated.map(n=>n.y),minX=Math.min(...xs),minY=Math.min(...ys),width=Math.max(10,Math.max(...xs)-minX),height=Math.max(10,Math.max(...ys)-minY);
 const pts=rotated.map(n=>({x:44+(n.x-minX)/width*120,y:45+(n.y-minY)/height*350}));
 return <section className="panel map-panel"><div className="panel-title"><h2>Route navigation</h2><div className="map-view-tabs"><button type="button" className={view==='2d'?'active':''} aria-pressed={view==='2d'} onClick={()=>setView('2d')}>2D map</button><button type="button" className={view==='3d'?'active':''} aria-pressed={view==='3d'} onClick={()=>setView('3d')}>3D view</button><button type="button" onClick={onGalaxy}>Galaxy</button></div></div><div className="map-surface">{route?<svg className="route-map" viewBox="0 0 350 455" role="img" aria-label={'Geographic route projection: '+nodes.map(n=>n.system).join(' to ')}>{pts.slice(1).map((p,i)=><line key={i} x1={pts[i].x} y1={pts[i].y} x2={p.x} y2={p.y} stroke="#ff9a24" strokeWidth="1.8" strokeDasharray={i===pts.length-2&&route.terminal?'4 4':undefined}/>)}{pts.map((p,i)=><g key={i}><circle cx={p.x} cy={p.y} r="10" fill={i===0||i===pts.length-1?'#ff9a24':'#111a20'} stroke="#ff9a24" strokeWidth="1.8"/><text x={p.x} y={p.y+4.5} textAnchor="middle" fill={i===0||i===pts.length-1?'#101518':'#e7edf1'} fontSize="13" fontWeight="600">{i+1}</text><text x={p.x+18} y={p.y-5} fill="#e4e9ec" fontSize="14">{nodes[i].name.length>22?nodes[i].name.slice(0,21)+'…':nodes[i].name}</text><text x={p.x+18} y={p.y+12} fill="#93a2ae" fontSize="12">{nodes[i].system.length>22?nodes[i].system.slice(0,21)+'…':nodes[i].system}</text></g>)}<g className="map-compass" fill="#9ba9b3" fontSize="10"><path d="M294 408v28m-14-14h28" stroke="#9ba9b3" strokeWidth=".7"/><text x="290" y="403">N</text><text x="314" y="425">E</text><text x="290" y="447">S</text><text x="266" y="425">W</text></g><g fill="#b2bec7" fontSize="11"><text x="18" y="420">{Math.round(width/3)} ly</text><path d="M18 435h68m-68-4v8m68-8v8" stroke="#86939d" strokeWidth=".8"/></g></svg>:<div className="map-empty"><Crosshair size={38}/><span>Awaiting flight plan</span><small>Your route's real system coordinates will appear here.</small></div>}</div><p className="map-caption">{view==='2d'?'Rotated X / Z projection':'Isometric X / Y / Z projection'} · Estimated transfers, not hyperspace navigation.</p></section>;
}
