import {useState,Fragment} from 'react';import {ChevronDown,Copy,Navigation,Route as RouteIcon,Coins,Milestone,Clock3} from 'lucide-react';
import type {Route,PlanResult,Cargo} from '../lib/types';import {age,credits,duration,number,routeCSV,download} from '../lib/format';import {routeStops,routeStats} from '../lib/presentation';
type Props={result:PlanResult|null;selected:number;setSelected:(n:number)=>void;onSave:()=>void;completed:number;setCompleted:(n:number)=>void;onReplan:()=>void;notify:(s:string)=>void;stale:boolean;historical:boolean;onShare:()=>void;onClear:()=>void};
export default function RouteView({result,selected,setSelected,onSave,completed,setCompleted,onReplan,notify,stale,historical,onShare,onClear}:Props){
 const [expanded,setExpanded]=useState<number|null>(null);const r=result?.routes[selected],stops=r?routeStops(r):[],stats=routeStats(r);
 async function copy(s:string){try{await navigator.clipboard.writeText(s);notify('Copied destination system.');}catch{notify('Clipboard unavailable. Select and copy the system name.');}}
 const exportCSV=()=>r&&download('edtrade-route.csv',routeCSV(r),'text/csv;charset=utf-8');
 return <><section className="panel route-panel"><div className="panel-title"><h1>Route itinerary</h1><div className="toolbar"><details className="actions-menu"><summary className="outline">Actions <ChevronDown size={11}/></summary><div className="action-popover"><button type="button" disabled={!r} onClick={exportCSV}>Export route CSV</button><button type="button" disabled={!r} onClick={()=>r&&void copy(r.legs.at(-1)!.to.system)}>Copy final system</button></div></details><button className="outline" type="button" disabled={!r} onClick={onSave}>Save route</button><button type="button" className="outline" onClick={onShare}>Share</button><button type="button" className="outline" disabled={!r} onClick={()=>{onClear();setExpanded(null);}}>Clear</button></div></div>
 {historical&&<div className="notice">Historical route — search again to refresh prices and availability.</div>}{stale&&<div className="notice">Settings changed. This itinerary uses the last search configuration.</div>}
 <div className="table-scroll itinerary-scroll"><table className="flight-itinerary"><colgroup><col className="marker-col"/><col className="station-col"/><col className="action-col"/><col className="commodity-col"/><col className="qty-col"/><col className="price-col"/><col className="total-col"/><col className="age-col"/></colgroup><thead><tr><th>#</th><th>Station (system)</th><th>Buy / sell</th><th>Commodity</th><th>Qty (t)</th><th>Price (Cr)</th><th>Total (Cr)</th><th>Quote age</th></tr></thead><tbody>{stops.map((s,i)=>{const isEnd=i===stops.length-1;return <Fragment key={i}><tr className={'stop-row '+(i>0&&i<=completed?'completed':'')}><td className={'stop-marker '+(i===0?'first ':'')+(isEnd?'last':'')}><span className={'stop-number '+(i===0||isEnd?'endpoint':'')}>{i+1}</span></td><td className="stop-station"><button type="button" className="station-button" aria-expanded={expanded===i} onClick={()=>setExpanded(expanded===i?null:i)}><b>{s.station.name}</b>{i===0||isEnd?<span className="station-tag">{i===0?'Start':'End'}</span>:null}</button><span className="station-system">{s.station.system}</span><small>{i===0?(r!.initialMinutes?'Positioning · '+duration(r!.initialMinutes):'Starting docked'):s.distance.toFixed(1)+' ly | '+s.jumps+' jumps | '+duration(s.minutes)}</small></td>
 <td>{s.actions.length?s.actions.map((a,j)=><div className="action-group" key={j}>{a.cargo.map((_,k)=><div className="trade-line" key={k}>{k===0&&<span className={'trade-badge '+a.type}>{a.type}</span>}</div>)}</div>):<span className="transfer-label">Transfer</span>}</td>
 <td>{s.actions.map((a,j)=><div className="action-group" key={j}>{a.cargo.map(c=><div className="trade-line commodity-name" title={c.name} key={c.key}>{c.name}</div>)}</div>)}</td><td>{s.actions.map((a,j)=><div className="action-group" key={j}>{a.cargo.map(c=><div className="trade-line" key={c.key}>{number(c.quantity)}</div>)}</div>)}</td><td>{s.actions.map((a,j)=><div className="action-group" key={j}>{a.cargo.map(c=><div className="trade-line" key={c.key}>{number(a.type==='buy'?c.buy:c.sell)}</div>)}</div>)}</td><td>{s.actions.map((a,j)=><div className="action-group" key={j}>{a.cargo.map(c=><div className="trade-line" key={c.key}>{number(c.quantity*(a.type==='buy'?c.buy:c.sell))}</div>)}</div>)}</td><td className="quote-cell" title={s.station.updated}>{age(s.station.updated).replace(' ago','')}{i>0&&i<=r!.legs.length&&<label className="stop-progress"><input type="checkbox" aria-label={'Complete trade leg '+i} checked={i<=completed} onChange={()=>setCompleted(i<=completed?i-1:i)}/><span>Done</span></label>}</td></tr>
 {expanded===i&&<tr className="manifest-row"><td colSpan={8}><div className="stop-manifest"><div className="manifest-heading"><span>{s.station.type} · {s.station.arrival===null?'Unknown approach':number(s.station.arrival)+' ls'} · Pad {['?','S','M','L'][s.station.pad]}</span><button type="button" className="outline" onClick={()=>void copy(s.station.system)}><Copy size={12}/> Copy system</button></div>{s.actions.map((a,j)=><div key={j}><b className={'manifest-action '+a.type}>{a.type==='buy'?'Buy cargo':'Sell cargo'}</b><table><thead><tr><th>Commodity</th><th>Tonnes</th><th>Supply</th><th>Demand</th><th>Est. trade profit</th></tr></thead><tbody>{a.cargo.map((c:Cargo)=><tr key={c.key}><td>{c.name}</td><td>{number(c.quantity)}</td><td>{number(c.supply)}</td><td>{number(c.demand)}</td><td className="amber">+{number(c.profit)} Cr</td></tr>)}</tbody></table></div>)}{i>0&&i<=r!.legs.length&&<p>Estimated balance after sale: {number(r!.legs[i-1].balance)} Cr</p>}</div></td></tr>}</Fragment>;})}</tbody></table></div>
 {!r&&<div className="empty-itinerary"><RouteIcon size={34}/><h2>{result?'No route fits these settings':'Ready for your next trading run'}</h2><p>{result?'Try a wider area, older market quotes or a lower minimum margin.':'Configure your ship and start location, then select Plan route.'}</p><small>Observed market prices. Ship-aware cargo. Multiple profitable stops.</small></div>}
 <div className="route-totals"><b>Route totals</b><span><Coins/>{r?r.legs.length:'—'} trades</span><span><Milestone/>{r?stats.distance.toFixed(1):'—'} ly</span><span><RouteIcon/>{r?stats.jumps:'—'} jumps</span><span><Clock3/>{r?duration(r.minutes):'—'}</span><span className="total-profit">Est. profit <strong>{r?number(r.profit):'—'} Cr</strong></span></div></section>
 <section className="panel alternatives-panel"><div className="panel-title"><h2>Alternative runs</h2><small>{result?.routes.length?'Compare routes based on your current configuration':'Awaiting your first route search'}</small></div><div className="table-scroll"><table className="alternative-table"><thead><tr><th>#</th><th>Route</th><th>Est. profit</th><th>Profit / hour</th><th>Time</th><th>Distance</th><th>Jumps</th><th>Notes</th><th>Action</th></tr></thead><tbody>{result?.routes.slice(0,3).map((run,i)=>{const st=routeStats(run);return <tr key={run.id} className={selected===i?'selected':''}><td><span className="alternative-letter">{'ABC'[i]}</span></td><td>{run.legs[0].from.system} → {run.terminal?.system??run.legs.at(-1)!.to.system}<small>{run.legs.length} trade legs · {st.stops.length} stations</small></td><td>{credits(run.profit)} Cr</td><td>{credits(run.rate)} Cr/h</td><td>{duration(run.minutes)}</td><td>{st.distance.toFixed(1)} ly</td><td>{st.jumps}</td><td><i className="dot"/>{selected===i?'Selected route':'Alternative path'}</td><td><button type="button" className="outline" aria-label={'Load alternative '+(i+1)} aria-pressed={selected===i} onClick={()=>{setSelected(i);setCompleted(0);setExpanded(null);}}>{selected===i?'Current':'Load'}</button></td></tr>;})}</tbody></table></div>{!result?.routes.length&&<div className="alternatives-empty">Best-found alternatives will be listed here.</div>}</section>
 {r&&<div className="flight-run-tools"><span>{completed} / {r.legs.length} trade legs completed · {Math.round(result!.elapsedMs)} ms search</span><button type="button" className="outline amber" disabled={!completed} onClick={onReplan}><Navigation size={13}/> Replan from completed stop</button></div>}
 </>;
}
export function routeEnd(r:Route,n:number){return r.legs[Math.max(0,Math.min(r.legs.length-1,n-1))];}
