import {useState} from 'react';import { Save,Trash2,Ship as ShipIcon,ChevronDown } from 'lucide-react';
import type {Ship,Settings,Station} from '../lib/types';import {Field,Numeric,Toggle} from './Fields';import {SystemInput} from './SystemInput';import {useStored} from '../lib/storage';import {shipSchema} from '../lib/validation';
const examples:Record<string,{cargo:number;pad:number}>={'Anaconda':{cargo:412,pad:3},'Type-9 Heavy':{cargo:752,pad:3},'Imperial Cutter':{cargo:720,pad:3},'Python':{cargo:280,pad:2},'Type-8 Transporter':{cargo:224,pad:2},'Asp Explorer':{cargo:96,pad:2},'Type-6 Transporter':{cargo:104,pad:2},'Cobra Mk III':{cargo:40,pad:1},'Custom ship':{cargo:100,pad:2}};
export default function ShipPanel({ship,setShip,settings,setSettings,stations,notify}:{ship:Ship;setShip:(s:Ship)=>void;settings:Settings;setSettings:(s:Settings)=>void;stations:Station[];notify:(s:string)=>void}){
 const [presets,setPresets]=useStored<{name:string;ship:Ship}[]>('edtrade.presets.v1',[],(v):v is {name:string;ship:Ship}[]=>Array.isArray(v)&&v.every(x=>typeof x.name==='string'&&shipSchema.safeParse(x.ship).success));
 const [name,setName]=useState('My trading ship'),[selected,setSelected]=useState('');const update=(key:keyof Ship,value:unknown)=>setShip({...ship,[key]:value});
 return <aside className="ship-panel panel"><div className="panel-title"><ShipIcon size={18}/><h2>Ship & run settings</h2></div><div className="panel-body">
 <Field label="Ship preset"><div className="preset-row"><select aria-label="Ship preset" value={selected} onChange={e=>{setSelected(e.target.value);const p=presets.find(p=>p.name===e.target.value);if(p)setShip(p.ship);}}><option value="">Unsaved configuration</option>{presets.map(p=><option key={p.name}>{p.name}</option>)}</select><button type="button" className="icon-button" title="Delete selected preset" aria-label="Delete selected preset" disabled={!selected} onClick={()=>{setPresets(presets.filter(p=>p.name!==selected));setSelected('');notify('Preset deleted.');}}><Trash2 size={16}/></button></div></Field>
 <Field label="Ship type"><select value={ship.name in examples?ship.name:'Custom ship'} onChange={e=>{const item=examples[e.target.value];setShip({...ship,name:e.target.value,...item});setSelected('');}}>{Object.keys(examples).map(n=><option key={n}>{n}</option>)}</select></Field>
 <Numeric label="Cargo capacity (t)" value={ship.cargo} onChange={v=>update('cargo',v)} min={1} max={2000}/>
 <Numeric label="Loaded jump range (ly)" value={ship.jump} onChange={v=>update('jump',v)} min={1} max={150} step={0.1}/>
 <Field label="Landing pad size"><select value={ship.pad} onChange={e=>update('pad',Number(e.target.value))}><option value={1}>Small (S)</option><option value={2}>Medium (M)</option><option value={3}>Large (L)</option></select></Field>
 <div className="divider"/><Numeric label="Total balance (Cr)" value={ship.budget} onChange={v=>update('budget',v)} min={1} max={1e12}/><Numeric label="Insurance reserve (Cr)" value={ship.reserve} onChange={v=>update('reserve',v)} max={1e12}/>
 <div className="divider"/><SystemInput label="Start system" value={settings.system} onChange={v=>setSettings({...settings,system:v,startStation:''})}/>
 <Field label="Start station (optional)" hint="Blank: includes travel to the first purchase."><input value={settings.startStation} onChange={e=>setSettings({...settings,startStation:e.target.value})} list="start-stations" maxLength={100} placeholder="Choose or type a station"/><datalist id="start-stations">{stations.filter(s=>s.system.toLowerCase()===settings.system.toLowerCase()).map(s=><option key={s.id} value={s.name}/>)}</datalist></Field>
 <details className="advanced"><summary>Advanced ship settings <ChevronDown size={15}/></summary><div className="details-body"><Toggle label="SCO drive" value={ship.sco} onChange={v=>update('sco',v)}/><Numeric label="Docking & trading (min / stop)" value={ship.dockingMinutes} onChange={v=>update('dockingMinutes',v)} min={0.5} max={30} step={0.5}/><Numeric label="Average hyperspace jump (sec)" value={ship.jumpSeconds} onChange={v=>update('jumpSeconds',v)} min={20} max={300}/><small>Ship selections are editable example loadouts. Use your actual outfitting values.</small></div></details>
 <Field label="Save as preset"><div className="preset-row"><input value={name} onChange={e=>setName(e.target.value)} maxLength={60} placeholder="Preset name"/><button type="button" className="outline orange" aria-label="Save ship preset" onClick={()=>{if(!shipSchema.safeParse(ship).success||!name.trim()){notify('Enter a preset name and valid ship values.');return;}const n=name.trim();setPresets([...presets.filter(p=>p.name!==n),{name:n,ship}].slice(-20));setSelected(n);notify('Ship preset saved in this browser.');}}><Save size={16}/></button></div></Field>
 </div></aside>;
}
